### ISSUE TITLE
Arduino code

### ISSUE THREAD

**Issue by madbobmcjim** [swindex/LEETArduinoPendant#1]
This looks like a really useful addon, do you happen to have an example arduino code file that could be used to build on? I've never looked at Firmata before.

**Comment by swindex** [comment]
Hi,
Just use these instructions on installing firmata on your Arduino:
https://www.instructables.com/Arduino-Installing-Standard-Firmata/
Firmata allows you to write all your code on the plugin side, and none on the Arduino.

**Comment by swindex** [comment]
Hi,
Just use these instructions on installing firmata on your Arduino:
https://www.instructables.com/Arduino-Installing-Standard-Firmata/
Firmata allows you to write all your code on the plugin side, and none on the Arduino.
