### ISSUE TITLE
Pinout

### ISSUE THREAD

**Issue by madbobmcjim** [swindex/LEETArduinoPendant#2]
Can you document the pinout for the Arduino?

**Comment by Buurte** [comment]
is there a pinout for the arduino?

**Comment by swindex** [comment]
@madbobmcjim , @Buurte 
I have added the board schematics to the Design Files section on the readme and the project home page:
https://zero-divide.net/?article_id=5319_custom-cnc-pendant-project
I am a noob at electonics design, so please let me know is something doesnt make sense of you want add your improvements.
