### ISSUE TITLE
no communication with arduino

### ISSUE THREAD

**Issue by Buurte** [swindex/LEETArduinoPendant#3]
i have installed the LEETArduinoPendant.dll &Solid.Arduino.dll library into the uccnc plugins folder. i build your schematic on a breadboard, but i dont think the plugin is communication with my arduino. the arduino is connected on COM4 i think this is what you have hardprogrammed. i looked a little inside your code and found the communication on COM4 but don't know if this is correct.

**Comment by swindex** [comment]
Hi,
Did you install the standard firmata library on to your Arduino?
Which Arduino version are you using?

**Comment by Buurte** [comment]
yes installed the standard firmata code, the version of the ide is 1.8.15. 
But with the newer software still the same.
Don't know if its helpfull but i use the uccnc software version 1.2111

**Comment by swindex** [comment]
Hi,
I have just wiped out everything on my dev PC and started from scratch.
As a result, please see the updated README file on the repository.

Mainly this part:
## 4. UCCNC Setup
* Download the latest LEETArduinoPendant from the releases and extract it to your PC.
* Copy the `LEETArduinoPendant.dll` plugin file to the `C:\UCCNC\Plugins` directory!
* Copy the `Solid.Arduino.dll` file from the `Solid.Arduino` release folder to the `C:\UCCNC` directory. (NOT to the Plugins!!)
* Please note that you might need to install `Arduino USB Driver` in order for your Arduino to work on the target computer!
* Launch UCCNC.exe, go to `Settings->Configure Plugins`, and mark the `LEET Arduino Pendant` plugin as `Enabled` and `Call startup`
* After everything is installed, Arduino is connected and UCCNC is running, press the "Enable" (+5v to D2-B-ENABLE ) button that will tell the plugin that the pendant is ready to send signals!
D13 (LED+) will then have a continuous +3.3V signal alerting you of that!

**PLEASE NOTE: When UCCNC and the plugin are up and running, `Enable` +5V signal to D2 pin is required to tell the plugin that the user wants to control the machine with the pendant. D13 Pin then will read +3.3V (connect that to a LED)

**Comment by swindex** [comment]
Closing the issue since with the updated information there shouldn't be issues running it
